import { DEMO_USER } from "@/lib/auth";
import type { Memory, RecalliaData } from "@/lib/types";

const SEED_CREATED_AT = "2026-04-27T00:00:00.000Z";

export const seedMemories: Memory[] = [
  {
    id: "memory-lived-in-hamburg",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Lived in Hamburg",
    description: "Lived in Hamburg before moving to Frankfurt.",
    startDate: "1990-01-01",
    endDate: "1994-12-31",
    dateConfidence: "approximate",
    location: "Hamburg",
    people: [],
    tags: ["place", "home"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-apprenticed-print-shop",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Apprenticed at print shop",
    description: "Learned print production basics in a small Hamburg print shop.",
    startDate: "1991-01-01",
    endDate: "1994-12-31",
    dateConfidence: "approximate",
    location: "Hamburg",
    people: [],
    tags: ["work", "learning"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-owned-beige-vw-golf-1",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Owned beige VW Golf 1",
    description:
      "A beige VW Golf 1 that anchored many memories from the 1990s in Germany.",
    startDate: "1992-01-01",
    endDate: "2000-12-31",
    dateConfidence: "approximate",
    location: "Germany",
    people: [],
    tags: ["car", "Germany", "personal artifact"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-lived-in-frankfurt",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Lived in Frankfurt",
    description: "Lived in Frankfurt during a formative stretch of the 1990s.",
    startDate: "1995-01-01",
    endDate: "1999-12-31",
    dateConfidence: "approximate",
    location: "Frankfurt",
    people: [],
    tags: ["place", "home"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-attended-evening-school",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Attended evening school",
    description: "Attended evening school while living in Frankfurt.",
    startDate: "1996-01-01",
    endDate: "1998-12-31",
    dateConfidence: "approximate",
    location: "Frankfurt",
    people: [],
    tags: ["education"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-worked-logistics-warehouse",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Worked at logistics warehouse",
    description: "Worked shifts at a Frankfurt logistics warehouse.",
    startDate: "1997-01-01",
    endDate: "2001-12-31",
    dateConfidence: "approximate",
    location: "Frankfurt",
    people: [],
    tags: ["work"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-owned-red-opel-corsa",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Owned red Opel Corsa",
    description: "A red Opel Corsa that overlapped with the last Frankfurt years.",
    startDate: "1998-01-01",
    endDate: "2002-12-31",
    dateConfidence: "approximate",
    location: "Germany",
    people: [],
    tags: ["car", "Germany", "personal artifact"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-completed-software-training",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Completed software training",
    description: "Completed a short software training program during the move toward IT work.",
    startDate: "1999-01-01",
    endDate: "2000-12-31",
    dateConfidence: "approximate",
    location: "Frankfurt",
    people: [],
    tags: ["education", "learning"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-lived-in-munich",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Lived in Munich",
    description: "Moved to Munich after the Frankfurt years.",
    startDate: "2000-01-01",
    endDate: "2004-12-31",
    dateConfidence: "approximate",
    location: "Munich",
    people: [],
    tags: ["place", "home"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-worked-it-support",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Worked first IT support job",
    description: "Worked a first IT support role after finishing the software training.",
    startDate: "2000-01-01",
    endDate: "2004-12-31",
    dateConfidence: "approximate",
    location: "Munich",
    people: [],
    tags: ["work", "technology"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-owned-silver-bmw-3-series",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Owned silver BMW 3 Series",
    description: "A silver BMW owned during the Munich period.",
    startDate: "2002-01-01",
    endDate: "2006-12-31",
    dateConfidence: "approximate",
    location: "Germany",
    people: [],
    tags: ["car", "Germany", "personal artifact"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-lived-in-berlin",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Lived in Berlin",
    description: "Lived in Berlin after Munich.",
    startDate: "2005-01-01",
    endDate: "2009-12-31",
    dateConfidence: "approximate",
    location: "Berlin",
    people: [],
    tags: ["place", "home"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-owned-blue-audi-a4",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Owned blue Audi A4",
    description: "A blue Audi A4 that carried the Berlin-to-Zurich years.",
    startDate: "2007-01-01",
    endDate: "2011-12-31",
    dateConfidence: "approximate",
    location: "Germany",
    people: [],
    tags: ["car", "Germany", "personal artifact"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-freelance-web-projects",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Freelance web projects",
    description: "Took on small freelance web projects while moving toward product work.",
    startDate: "2009-01-01",
    endDate: "2012-12-31",
    dateConfidence: "approximate",
    location: "Berlin",
    people: [],
    tags: ["work", "technology"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-lived-in-zurich",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Lived in Zurich",
    description: "Lived in Zurich during a later career chapter.",
    startDate: "2010-01-01",
    endDate: "2013-12-31",
    dateConfidence: "approximate",
    location: "Zurich",
    people: [],
    tags: ["place", "home"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  },
  {
    id: "memory-weekend-product-course",
    userId: DEMO_USER.id,
    status: "saved",
    title: "Weekend product course",
    description: "Completed a weekend product management course while in Zurich.",
    startDate: "2011-01-01",
    endDate: "2012-12-31",
    dateConfidence: "approximate",
    location: "Zurich",
    people: [],
    tags: ["education", "learning"],
    linkedMemoryIds: [],
    createdAt: SEED_CREATED_AT,
    updatedAt: SEED_CREATED_AT
  }
];

export function createSeedData(): RecalliaData {
  return {
    memories: seedMemories.map((memory) => ({
      ...memory,
      people: [...memory.people],
      tags: [...memory.tags],
      linkedMemoryIds: [...memory.linkedMemoryIds]
    })),
    aiRuns: []
  };
}
